import asyncio
import subprocess
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import edge_tts

W,H=720,1280
BG="#FFFAF4"; PURPLE="#7847D8"; LAVENDER="#F6EDFF"; DARK="#18151B"; MUTED="#665F69"
VOICE="es-AR-ElenaNeural"; RATE="-5%"
OUT=Path("lumina_days12_30_build"); OUT.mkdir(exist_ok=True)

DAYS={
12:{"title":"Las trampas de mi mente","focus":"Hoy vas a reconocer seis distorsiones cognitivas del workbook: personalización, adivinar el futuro, maximizar o minimizar, lectura de mente, pensamiento dicotómico y comparación falsa.","signals":"Prestá atención a frases como: seguro fue por mí; ya sé que va a salir mal; esto es terrible; sé lo que piensan de mí; o es perfecto o es un fracaso; todos pueden menos yo.","example":"Si alguien tarda en responder un mensaje, tu mente puede personalizarlo, leer la mente y adivinar un rechazo. El hecho observable, en cambio, es solamente que todavía no respondió.","exercise":"Elegí un pensamiento de hoy y preguntate qué trampa mental aparece. Nombrarla no elimina el pensamiento, pero crea distancia entre lo que pensás y lo que realmente sabés.","reframe":"Una distorsión no significa que estés inventando todo. Significa que tu mente está interpretando la realidad de una forma parcial o extrema.","micro":"Durante las próximas 24 horas, cada vez que aparezca un pensamiento intenso, probá decir: esto puede ser una interpretación. Después buscá qué distorsión se parece más.","next":"¿Qué evidencia tengo realmente?"},
13:{"title":"¿Qué evidencia tengo realmente?","focus":"Hoy vamos a diferenciar una conclusión automática de la evidencia que realmente la sostiene.","signals":"Una idea puede sentirse completamente cierta y, aun así, estar basada en suposiciones, recuerdos selectivos, emociones o una única experiencia.","example":"Pensar no le importo porque no me escribió es una interpretación. La evidencia puede incluir que no escribió hoy, pero también otros datos del vínculo que tu mente dejó afuera.","exercise":"Escribí un pensamiento difícil. Debajo hacé dos columnas: evidencia que lo apoya y evidencia que no lo apoya. Usá hechos observables, no nuevas interpretaciones.","reframe":"Buscar evidencia no es convencerte de que todo está bien. Es construir una mirada más completa y menos dominada por una sola conclusión.","micro":"Cuando notes una certeza dolorosa, preguntate: ¿qué dato concreto tengo?, ¿qué estoy suponiendo?, ¿qué información falta?","next":"Preguntas que cambian pensamientos"},
14:{"title":"Preguntas que cambian pensamientos","focus":"Hoy vas a usar preguntas de reestructuración cognitiva para revisar pensamientos rígidos, amenazantes o descalificadores.","signals":"Las preguntas útiles no buscan pensamiento positivo. Buscan precisión: qué sé, qué no sé, qué otra explicación existe y qué le diría a alguien que quiero.","example":"Ante voy a fracasar, podés preguntar: ¿qué evidencia tengo?, ¿estoy prediciendo el futuro?, ¿qué resultados intermedios son posibles?, ¿qué podría hacer si algo sale mal?","exercise":"Elegí un pensamiento y respondé al menos cuatro preguntas: qué evidencia lo apoya, qué evidencia lo cuestiona, qué alternativa existe y qué respuesta sería más equilibrada.","reframe":"Una buena pregunta abre posibilidades. No tiene que eliminar la emoción para ser útil; alcanza con reducir la certeza de la interpretación inicial.","micro":"Hoy no discutas con todos tus pensamientos. Elegí uno y hacé una sola pregunta que te devuelva curiosidad en lugar de certeza.","next":"Mi primera reestructuración completa"},
15:{"title":"Mi primera reestructuración completa","focus":"Hoy vas a integrar situación, pensamiento, emoción, evidencia y pensamiento alternativo en un registro completo.","signals":"La secuencia importa: primero describimos qué pasó, después qué pensaste, qué sentiste y qué hiciste. Recién entonces revisamos la interpretación.","example":"Situación: no me respondieron. Pensamiento: hice algo mal. Emoción: ansiedad. Evidencia: no hubo respuesta todavía. Alternativa: pueden existir muchas razones y puedo esperar antes de concluir.","exercise":"Elegí una situación reciente. Registrá situación, pensamiento automático, emoción de cero a cien, evidencia a favor, evidencia en contra y una respuesta alternativa realista.","reframe":"El pensamiento alternativo no tiene que ser perfecto ni tranquilizador. Tiene que ser más equilibrado y coherente con todos los datos disponibles.","micro":"Guardá tu registro. Mañana releelo y observá si la intensidad emocional cambia cuando tu interpretación incluye más información.","next":"Hablarme como alguien a quien quiero"},
16:{"title":"Hablarme como alguien a quien quiero","focus":"Hoy empieza una fase distinta: no solo cuestionar lo que pensás, sino observar cómo te tratás cuando algo duele o no sale como esperabas.","signals":"La autocrítica suele aparecer con insultos, desprecio, amenazas internas o reglas como no podés equivocarte, tendrías que poder sola o nunca hacés nada bien.","example":"Podés reconocer un error diciendo esto no salió como quería y necesito repararlo, sin agregar soy un desastre. Responsabilidad y maltrato no son lo mismo.","exercise":"Tomá una frase dura que te dijiste esta semana. Imaginá que una persona querida te cuenta exactamente la misma situación. Escribí qué le responderías y adaptalo para vos.","reframe":"Tratarte con respeto no significa justificar todo. Significa corregir, aprender y poner límites sin convertir cada error en una condena sobre quién sos.","micro":"Durante 24 horas, cuando notes una frase cruel hacia vos, reemplazala por una frase firme pero respetuosa.","next":"No soy solamente mis defectos"},
17:{"title":"No soy solamente mis defectos","focus":"Hoy vas a revisar una tendencia común: reducir tu identidad a lo que te cuesta, a lo que te falta o a aquello que querés cambiar.","signals":"Cuando tu autoconcepto se vuelve estrecho, un defecto parece explicar toda tu persona y los aspectos valiosos quedan fuera de foco.","example":"Ser desorganizada en algunas áreas no significa ser incapaz. Podés tener dificultades reales y, al mismo tiempo, ser afectuosa, persistente, creativa o responsable en otros contextos.","exercise":"Escribí cinco aspectos tuyos que suelen quedar invisibles cuando estás mal: capacidades, valores, esfuerzos, formas de vincularte o aprendizajes que sí forman parte de vos.","reframe":"Una mirada realista incluye fortalezas y dificultades. No necesitás negar lo que querés mejorar para dejar de definirte exclusivamente por eso.","micro":"Hoy, cada vez que aparezca soy así, agregá: esta es una parte de mí, no toda mi identidad.","next":"Lo que puedo controlar"},
18:{"title":"Lo que puedo controlar","focus":"Hoy vas a aplicar el autorespeto a una pregunta práctica: dónde poner tu energía cuando algo te preocupa.","signals":"Podés influir en tus decisiones, acciones, palabras, límites y preparación. No podés controlar por completo la opinión, conducta o reacción de otras personas.","example":"Antes de una conversación podés preparar lo que querés decir y elegir tu tono. No podés garantizar que la otra persona lo entienda, lo apruebe o responda como esperás.","exercise":"Dividí una hoja en dos: depende de mí y no depende de mí. Colocá cada preocupación donde corresponde y elegí una acción concreta solo de la primera columna.","reframe":"Aceptar que algo no depende de vos no significa resignarte. Significa dejar de exigir control donde solo existe influencia o incertidumbre.","micro":"Cuando notes que estás intentando controlar una reacción ajena, volvé a esta pregunta: ¿qué acción sí está disponible para mí ahora?","next":"Mis valores como brújula"},
19:{"title":"Mis valores como brújula","focus":"Hoy vamos a trabajar con valores: direcciones que querés encarnar, incluso cuando no podés controlar el resultado.","signals":"Un valor no es una meta que se termina. Honestidad, cuidado, crecimiento, libertad o respeto pueden expresarse de muchas maneras a lo largo del tiempo.","example":"Si valorás el cuidado, no necesitás esperar a sentirte perfectamente motivada. Podés expresarlo hoy en una conversación, en un límite o en cómo organizás tu descanso.","exercise":"Elegí cinco valores importantes y reducilos a tres. Para cada uno, escribí una acción pequeña que lo represente durante esta semana.","reframe":"Los valores no te dicen qué deberías querer para complacer a otros. Te ayudan a elegir qué tipo de persona querés practicar ser en tus decisiones.","micro":"Antes de una decisión pequeña, preguntate: ¿qué opción se acerca más a la persona que quiero ser?","next":"Reconocer lo que sí hago"},
20:{"title":"Reconocer lo que sí hago","focus":"Hoy vas a entrenar una autoevaluación más equilibrada mediante el reconocimiento de esfuerzos y logros cotidianos.","signals":"La mente puede descartar lo que hacés bien con frases como era mi obligación, cualquiera puede o todavía falta demasiado.","example":"Levantarte en un día difícil, pedir ayuda, terminar una tarea, descansar a tiempo o intentar algo nuevo pueden ser logros aunque no sean espectaculares.","exercise":"Anotá entre cuatro y cinco logros de hoy. Junto a cada uno escribí qué fortaleza, valor o esfuerzo hubo detrás. Elegí uno y completá: me felicito por.","reframe":"Reconocer un logro no es inflar tu ego. Es evitar que tu evaluación personal esté construida únicamente con errores, pendientes y comparaciones.","micro":"Antes de dormir, nombrá tres cosas que sí hiciste y una cualidad que estuvo presente en alguna de ellas.","next":"Respetarme también es poner límites"},
21:{"title":"Respetarme también es poner límites","focus":"Hoy vas a mirar los límites como una forma de autorespeto y comunicación, no como una manera de castigar o controlar a otras personas.","signals":"Tal vez necesitás un límite cuando acumulás resentimiento, agotamiento, invasión de tiempo, presión o la sensación repetida de decir sí cuando querías decir no.","example":"Un límite puede ser: hoy no puedo ayudarte, necesito que me avises antes, no quiero hablar de este tema de esa manera o puedo quedarme hasta determinada hora.","exercise":"Elegí una situación que te sobrecarga. Escribí qué necesitás, qué conducta querés cambiar y una frase breve que comunique el límite sin justificarte de más.","reframe":"Un límite sano habla de lo que vos harás, aceptarás o necesitás. No garantiza que la otra persona esté de acuerdo.","micro":"Practicá hoy un límite pequeño y específico. Observá la incomodidad sin usarla como prueba de que hiciste algo malo.","next":"El miedo a decir que no"},
22:{"title":"El miedo a decir que no","focus":"Hoy vas a separar el límite que necesitás del miedo que aparece al imaginar rechazo, enojo o decepción.","signals":"Muchas veces el sí automático busca evitar culpa, tensión, conflicto o la idea de que alguien puede pensar mal de vos.","example":"Antes de aceptar un pedido, podés sentir que si decís no la relación se va a dañar. Eso es una predicción, no un hecho confirmado.","exercise":"Pensá en un pedido difícil. Completá: si digo que no, temo que. Después preguntate qué evidencia tenés y cómo podrías cuidarte si la otra persona se incomoda.","reframe":"El objetivo no es dejar de sentir miedo antes de poner un límite. Es evitar que el miedo tome todas las decisiones por vos.","micro":"Hoy esperá unos segundos antes de responder un pedido. Preguntate qué elegirías si no tuvieras que eliminar inmediatamente la incomodidad.","next":"La culpa después de poner límites"},
23:{"title":"La culpa después de poner límites","focus":"Hoy vas a diferenciar culpa útil de culpa aprendida. Sentir culpa no demuestra automáticamente que hayas hecho algo incorrecto.","signals":"La culpa útil puede señalar daño real y necesidad de reparar. La culpa aprendida puede aparecer simplemente porque dejaste de cumplir una expectativa ajena.","example":"Si insultaste a alguien, puede corresponder reparar. Si dijiste con respeto que no podías hacer un favor, la incomodidad del otro no convierte tu límite en una agresión.","exercise":"Revisá un límite reciente. Describí qué hiciste, si hubo daño real, qué parte podría repararse y qué parte necesitás sostener aunque la culpa siga presente.","reframe":"Podés escuchar la culpa sin obedecerla automáticamente. Reparar no es lo mismo que retirar todos tus límites.","micro":"Cuando aparezca culpa, describí primero el hecho sin interpretaciones. Después decidí si corresponde reparar o simplemente tolerar la incomodidad.","next":"Pedir lo que necesito"},
24:{"title":"Pedir lo que necesito","focus":"Hoy vas a transformar una necesidad interna en un pedido claro, específico y respetuoso.","signals":"Cuando no pedimos directamente, podemos esperar que el otro adivine, usar indirectas o acumular frustración porque una necesidad nunca fue expresada.","example":"En lugar de nunca estás para mí, un pedido puede ser: esta semana necesito que reservemos media hora para hablar sin teléfonos.","exercise":"Elegí una necesidad actual. Describí la situación, nombrá lo que necesitás y convertí esa necesidad en una petición observable y concreta.","reframe":"Pedir no es exigir. La otra persona puede aceptar, negociar o decir que no, y tu necesidad sigue siendo válida aunque no se satisfaga exactamente como querías.","micro":"Formulá hoy un pedido en una sola frase: claro, específico y sin esperar que la otra persona lea tu mente.","next":"Elegirme sin abandonar a los demás"},
25:{"title":"Elegirme sin abandonar a los demás","focus":"Hoy vamos a buscar una posición intermedia entre sacrificarte siempre por otros y desconectarte por completo de sus necesidades.","signals":"El autoabandono aparece cuando tu necesidad queda automáticamente última, aun cuando existe una alternativa más equilibrada.","example":"Podés querer acompañar a alguien y, al mismo tiempo, necesitar descansar. Tal vez la respuesta no sea todo o nada, sino ofrecer una ayuda que puedas sostener.","exercise":"Escribí qué necesitás vos, qué podría necesitar la otra persona, qué podés ofrecer sin excederte y qué límite necesitás mantener.","reframe":"Cuidar un vínculo no exige desaparecer. Dos necesidades pueden coexistir incluso cuando no existe una solución perfecta.","micro":"En una decisión de hoy, incluí conscientemente una necesidad tuya antes de responder qué vas a hacer por los demás.","next":"La vida que quiero sostener"},
26:{"title":"La vida que quiero sostener","focus":"Entramos en la fase final. Hoy vas a mirar qué aprendizajes de estos días querés convertir en una forma de vivir, no solo en ejercicios aislados.","signals":"Una vida sostenible no se construye con cambios enormes todos los días, sino con elecciones repetidas que respetan tus valores, tus límites y tus necesidades.","example":"Quizá querés sostener una vida donde descanses antes de agotarte, hables con más respeto hacia vos o revises tus pensamientos antes de creerlos automáticamente.","exercise":"Completá tres frases: quiero más de esto en mi vida; quiero menos de esto; quiero proteger esto aunque tenga días difíciles.","reframe":"No necesitás mantener todo lo aprendido al mismo tiempo. Elegir dos o tres pilares claros suele ser más sostenible que intentar hacerlo perfecto.","micro":"Elegí un hábito, una relación y una forma de hablarte que quieras cuidar durante el próximo mes.","next":"Mi rutina de autoestima"},
27:{"title":"Mi rutina de autoestima","focus":"Hoy vas a crear una rutina mínima para sostener lo trabajado: observarte, cuidarte, reconocer tus logros y actuar según tus valores.","signals":"Una rutina útil tiene que ser suficientemente pequeña para existir también en semanas imperfectas, no solo cuando tenés tiempo y energía de sobra.","example":"Puede incluir dos minutos de registro de pensamientos, un límite pendiente, tres logros antes de dormir y una acción semanal conectada con un valor.","exercise":"Diseñá una rutina de mañana, una de cierre del día y una práctica semanal. Cada una debe poder hacerse en pocos minutos.","reframe":"La constancia no significa nunca interrumpir. Significa tener una forma simple de volver cuando te alejás de la práctica.","micro":"Probá hoy la versión más corta de tu rutina. Después ajustala según lo que realmente puedas sostener.","next":"Qué hacer en un día difícil"},
28:{"title":"Qué hacer en un día difícil","focus":"Hoy vamos a preparar un plan para esos días en los que pensar con claridad, cuidarte o aplicar herramientas cuesta mucho más.","signals":"En un día difícil, tu objetivo puede bajar de crecer a estabilizarte: comer, hidratarte, descansar, reducir exigencias y pedir apoyo si lo necesitás.","example":"No hace falta resolver tu vida a las once de la noche después de un día agotador. A veces la intervención más útil es posponer decisiones importantes hasta estar más regulada.","exercise":"Armá tu plan de mínimo viable: tres necesidades básicas, dos personas o recursos de apoyo, una frase que quieras recordar y una decisión que conviene no tomar en crisis.","reframe":"Un mal día no invalida tu proceso. La capacidad de cuidarte cuando estás peor también forma parte del progreso.","micro":"Guardá tu plan en un lugar fácil de encontrar. La idea es no tener que inventarlo de cero cuando estés saturada.","next":"Carta a mi yo futuro"},
29:{"title":"Carta a mi yo futuro","focus":"Hoy vas a escribirle a la versión de vos que va a necesitar recordar lo aprendido cuando vuelvan la duda, la exigencia o la comparación.","signals":"Una carta al futuro puede funcionar como memoria externa: conserva ideas que en un momento difícil quizá tu mente no pueda recuperar con facilidad.","example":"Podés recordarte qué descubriste sobre tus valores, qué límites necesitás, qué pensamientos no querés volver a tratar como hechos y qué logros solés minimizar.","exercise":"Escribí una carta empezando por: si estás leyendo esto en un día difícil, quiero que recuerdes. Incluí aprendizajes, advertencias cariñosas y acciones concretas para volver a vos.","reframe":"No escribas para una versión perfecta de vos. Escribí para una persona real que a veces se va a sentir cansada, insegura o confundida.","micro":"Terminá la carta con tres instrucciones simples que puedan hacerse incluso en un día de poca energía.","next":"Volver a mirarme"},
30:{"title":"Volver a mirarme","focus":"Llegaste al Día 30. Hoy no vamos a buscar una versión nueva de vos, sino volver a mirar a la misma persona con más información, más perspectiva y más respeto.","signals":"A lo largo del curso observaste autoconcepto, exigencias, expectativas, pensamientos, autocompasión, valores, límites, necesidades y formas de sostenerte.","example":"Tal vez algunas dificultades siguen ahí. El cambio no consiste en no volver a dudar, sino en tener más herramientas para no convertir cada duda en una definición sobre quién sos.","exercise":"Volvé a la imagen o descripción con la que empezaste. Escribí qué ves hoy que antes no estabas registrando y qué querés seguir practicando durante los próximos treinta días.","reframe":"La autoestima no es una meta que se completa. Es una relación que se construye una y otra vez en la forma en que te mirás, te hablás y elegís cuidarte.","micro":"Elegí tres compromisos de continuidad. Que sean concretos, realistas y tuyos. Este día cierra el recorrido, no el proceso.","next":"Tu etapa de mantenimiento"}
}

def font(size,bold=False):
    p="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    return ImageFont.truetype(p,size)

def wrap_px(draw,text,fnt,max_width):
    out=[]
    for para in text.split("\n"):
        words=para.split()
        if not words: out.append(""); continue
        cur=words[0]
        for w in words[1:]:
            test=cur+" "+w
            if draw.textbbox((0,0),test,font=fnt)[2] <= max_width: cur=test
            else: out.append(cur); cur=w
        out.append(cur)
    return out

def draw_multiline(draw,x,y,lines,fnt,fill,spacing=12):
    for line in lines:
        draw.text((x,y),line,font=fnt,fill=fill)
        b=draw.textbbox((x,y),line if line else "Ag",font=fnt)
        y += (b[3]-b[1])+spacing
    return y

def scenes_for(day,d):
    return [
      {"label":f"DÍA {day} · {day}/30","title":d["title"],"body":"Una práctica guiada para observar, comprender y elegir con más conciencia.","speech":f"Bienvenida al Día {day} de LUMINA. {d['focus']} No necesitás hacer este ejercicio de manera perfecta. La propuesta es observar con curiosidad qué pasa en vos y sumar una herramienta que puedas usar en tu vida real."},
      {"label":"IDEA CENTRAL","title":"Qué vamos a observar hoy","body":d["focus"],"speech":f"La idea central de hoy es esta. {d['focus']} A veces la mente intenta resolver rápido lo que sentimos y termina usando reglas, conclusiones o hábitos que parecen automáticos. Hoy vamos a hacerlos un poco más visibles para que tengas más margen de elección."},
      {"label":"SEÑALES","title":"Cómo puede aparecer en tu día","body":d["signals"],"speech":f"¿Cómo puede aparecer esto en la vida cotidiana? {d['signals']} No tomes estas señales como una lista para juzgarte. Usalas como pistas. Cuanto antes reconocés un patrón, más fácil es decidir si querés seguirlo o responder de otra manera."},
      {"label":"EJEMPLO","title":"Llevémoslo a una situación concreta","body":d["example"],"speech":f"Veamos un ejemplo. {d['example']} Lo importante del ejemplo no es copiar una respuesta exacta, sino notar la diferencia entre reaccionar automáticamente y detenerte lo suficiente como para mirar más información."},
      {"label":"EJERCICIO CENTRAL","title":"Ahora trabajalo con una situación tuya","body":d["exercise"],"speech":f"Vamos al ejercicio del Día {day}. {d['exercise']} Tomate unos minutos. Escribí aunque al principio no estés segura. Muchas veces la claridad aparece mientras ordenamos la experiencia en palabras.","pause_after":6},
      {"label":"UNA MIRADA MÁS EQUILIBRADA","title":"No buscamos perfección","body":d["reframe"],"speech":f"Quiero que te quedes con esta idea. {d['reframe']} El objetivo de LUMINA no es enseñarte a pensar siempre bien, sentirte bien todo el tiempo ni eliminar cualquier incomodidad. Es ayudarte a relacionarte con vos de una manera más consciente, realista y respetuosa."},
      {"label":"MICROACCIÓN · 24 HORAS","title":"Una práctica pequeña para hoy","body":d["micro"],"speech":f"Para las próximas veinticuatro horas, probá esto. {d['micro']} Elegí una sola oportunidad para practicarlo. Una acción pequeña repetida en la vida real suele enseñar más que intentar cambiar todo de una vez."},
      {"label":f"DÍA {day} COMPLETADO","title":"Cerrá el día registrando lo que aprendiste","body":f"{day} / 30 · Mañana: {d['next']}","speech":f"Completaste el Día {day} de LUMINA. Antes de cerrar, preguntate qué idea de hoy querés recordar y qué acción concreta vas a probar. No necesitás sentir un cambio enorme para que esta práctica tenga valor. Mañana seguimos con: {d['next']}. Nos vemos en el próximo día."}
    ]

def make_slide(scene,idx,total):
    img=Image.new("RGB",(W,H),BG); d=ImageDraw.Draw(img)
    d.text((50,55),"LUMINA",font=font(28,True),fill=PURPLE)
    d.rounded_rectangle((560,45,670,90),radius=22,fill=LAVENDER)
    d.text((615,67),f"{idx+1}/{total}",font=font(18,True),fill=PURPLE,anchor="mm")
    d.rounded_rectangle((50,112,670,122),radius=5,fill="#E9DDF8")
    d.rounded_rectangle((50,112,50+max(30,int(620*(idx+1)/total)),122),radius=5,fill=PURPLE)
    d.text((50,170),scene["label"],font=font(22,True),fill=PURPLE)
    tf=font(48 if len(scene["title"])<48 else 40,True)
    y=draw_multiline(d,50,225,wrap_px(d,scene["title"],tf,620),tf,DARK,12)+35
    bf=font(27); lines=wrap_px(d,scene["body"],bf,540); card_h=max(230,80+len(lines)*42)
    d.rounded_rectangle((50,y,670,min(1060,y+card_h)),radius=32,fill=LAVENDER)
    by=y+42
    for line in lines[:16]:
        d.text((90,by),line,font=bf,fill=DARK); by+=42
    d.text((50,1120),"OBSERVÁ · CUESTIONÁ · ELEGÍ",font=font(19,True),fill=PURPLE)
    d.text((50,1165),"LUMINA · 30 días para volver a vos",font=font(17),fill=MUTED)
    return img

async def synth(text,out_mp3):
    await edge_tts.Communicate(text=text,voice=VOICE,rate=RATE).save(str(out_mp3))

def duration(path):
    r=subprocess.run(["ffprobe","-v","error","-show_entries","format=duration","-of","default=noprint_wrappers=1:nokey=1",str(path)],capture_output=True,text=True,check=True)
    return float(r.stdout.strip())

def make_segment(img_path,audio_path,out_path):
    dur=duration(audio_path)
    subprocess.run(["ffmpeg","-y","-loop","1","-framerate","30","-i",str(img_path),"-i",str(audio_path),"-vf","scale=720:1280,format=yuv420p","-c:v","libx264","-preset","veryfast","-tune","stillimage","-c:a","aac","-b:a","144k","-ar","48000","-ac","2","-t",f"{dur:.3f}","-shortest",str(out_path)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)

def add_pause(img_path,seconds,out_path):
    subprocess.run(["ffmpeg","-y","-loop","1","-framerate","30","-i",str(img_path),"-f","lavfi","-i","anullsrc=r=48000:cl=stereo","-vf","scale=720:1280,format=yuv420p","-c:v","libx264","-preset","veryfast","-tune","stillimage","-c:a","aac","-b:a","144k","-t",str(seconds),"-shortest",str(out_path)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)

async def build_day(day,d):
    daydir=OUT/f"day{day}"; daydir.mkdir(exist_ok=True)
    scenes=scenes_for(day,d); entries=[]
    for i,s in enumerate(scenes):
        img=daydir/f"slide_{i:02d}.png"; aud=daydir/f"voice_{i:02d}.mp3"; seg=daydir/f"seg_{i:02d}.mp4"
        make_slide(s,i,len(scenes)).save(img)
        await synth(s["speech"],aud)
        make_segment(img,aud,seg); entries.append(seg)
        if s.get("pause_after"):
            p=daydir/f"pause_{i:02d}.mp4"; add_pause(img,s["pause_after"],p); entries.append(p)
    cf=daydir/"concat.txt"; cf.write_text("\n".join(f"file '{p.resolve()}'" for p in entries),encoding="utf-8")
    outfile=Path(f"LUMINA_Dia{day}_voz_natural.mp4")
    subprocess.run(["ffmpeg","-y","-f","concat","-safe","0","-i",str(cf),"-c","copy",str(outfile)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    print(day, duration(outfile))

async def main():
    for day in range(12,31):
        await build_day(day,DAYS[day])

if __name__=="__main__": asyncio.run(main())
